version: '3.8'

services:
  web:
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: "1"
    volumes:
      - ./:/app
      - ./logs/web:/var/log/app
    ports:
      - "8000:8000"

